[package]
name = "rs48_lib"
version = "1.3.1"
edition = "2021"
description = "components of rs48"
license = "MIT"
authors = ["JOLIMAITRE Matthieu <matthieu@imagevo.fr>"]

[dependencies]
rand = "0.8"
rayon = "1.5.3"
termion = "1.5"
